INSERT INTO VACUNA VALUES (1,'Pfizer',90,'N/A','-70 °C','Descongelar el vial exponiéndolo a 25 grados centígrados durante 30 minutos.');
INSERT INTO VACUNA VALUES (2,'Moderna',96,'N/A','-70 °C','Después de retirar la primera dosis, el vial debe mantenerse entre 2° y 25°C (36° a 77°F). Anote la fecha y la hora del primer uso en el frasco. Deseche el frasco después de seis horas. No vuelva a congelar.');
INSERT INTO VACUNA VALUES (3,'Johnson & Johnson',66,'N/A','-20 °C','Inspeccionar visualmente los viales de la vacuna contra la COVID-19 de Janssen para detectar la presencia de partículas y cambio de color antes de su administración.');
INSERT INTO VACUNA VALUES (4,'AstraZeneca',60,'N/A','5 °C','No puede ser congelada, debe permanecer en temperaturar de 2°C a -8°c');
INSERT INTO VACUNA VALUES (5,'Sinopharm',79,'N/A','5 °C','No puede ser congelada, debe permanecer en temperaturar de 2°C a -8°c');



INSERT INTO VACUNA VALUES (6,'Sputnik V',92,'N/A','-18 °C','El contenido del vial debe descongelarse para su aplicación (tiempo estimado: entre 7 y 10 minutos dependiendo de la temperatura ambiental) y debe administrarse en un plazo máximo de 2 horas luego de descongelado. ');
INSERT INTO VACUNA VALUES (7,'CoronaVac',89,'N/A','6 °C','La vía de administración recomendada es inyección intramuscular en la parte superior del brazo en el músculo deltoides. Agitar bien antes de usar');
INSERT INTO VACUNA VALUES (8,'Sinovac',87,'N/A','4 °C','La vía de administración recomendada es inyección intramuscular en la parte superior del brazo en el músculo deltoides. Agitar bien antes de usar');
INSERT INTO VACUNA VALUES (9,'ARNm',90,'N/A','-70 °C','Siempre mantenerse congelado al almacenar debido a que se descompone con facilidad y rapidez a menos que se mantenga a temperaturas bajas.');


INSERT INTO VACUNA VALUES (10,'',,'N/A','','');
INSERT INTO VACUNA VALUES (11,'',,'N/A','','');
INSERT INTO VACUNA VALUES (12,'',,'N/A','','');
INSERT INTO VACUNA VALUES (13,'',,'N/A','','');
INSERT INTO VACUNA VALUES (14,'',,'N/A','','');
INSERT INTO VACUNA VALUES (15,'',,'N/A','','');