INSERT INTO VARIANTE VALUES(1,'Gamma','Podría escapar a las respuestas inmunitarias tanto naturales como provocadas por la vacuna.',1);
INSERT INTO VARIANTE VALUES(2,'Delta','Los expertos creen que la variante delta es probablemente más transmisible.',1);
INSERT INTO VARIANTE VALUES(3,'Iota','Hace que el virus sea menos reconocible para el sistema inmunológico.',1);
INSERT INTO VARIANTE VALUES(4,'Beta','Se sospecha ayuda a que otras variantes sean más contagiosas.',1);
INSERT INTO VARIANTE VALUES(5,'Lambda','Se detectaron mutaciones en esta variante que se sospecha la pueden hacer más transmisible.',1);